# 기본 이미지로 Python 3.9을 사용
FROM python:3.9.13

# 컨테이너 내에서 코드가 실행될 디렉토리 생성 및 설정
WORKDIR /navi-media

# 현재 디렉토리의 requirements.txt 파일을 컨테이너의 /app 디렉토리로 복사
COPY requirements.txt .

# requirements.txt에 명시된 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 현재 디렉토리의 모든 파일을 컨테이너의 /navi-media 디렉토리로 복사
COPY . .

# 컨테이너가 시작될 때 실행될 명령어 설정
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8083"]
