# 1단계: Node.js를 사용하여 React 애플리케이션 빌드
FROM node:20.11.1 as build-stage
WORKDIR /app

# package.json과 package-lock.json을 복사하고 의존성 설치
COPY package.json package-lock.json ./
RUN npm install

# 프로젝트 소스 코드 복사
COPY . .

# React 애플리케이션 빌드
RUN npm run build

# 2단계: Nginx를 사용하여 빌드된 애플리케이션 서빙
FROM nginx:alpine
# 빌드 결과물을 Nginx가 서빙할 디렉토리로 복사
COPY --from=build-stage /app/build /usr/share/nginx/html

# 필요한 경우 Nginx 설정 파일을 커스터마이징하고 복사
# COPY nginx.conf /etc/nginx/nginx.conf

# 컨테이너가 80 포트에서 수신하도록 설정
EXPOSE 80

# Nginx 시작
CMD ["nginx", "-g", "daemon off;"]
